/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes } = useGLTF("./bun_zipper.gltf");

  return (
    <group {...props} dispose={null}>
      <points
        castShadow
        receiveShadow
        geometry={nodes.model.geometry}
        material={nodes.model.material}
      >
        <pointsMaterial color="#FFFFFF" size={0.015} sizeAttenuation />
      </points>
    </group>
  );
}

useGLTF.preload("./bun_zipper.gltf");
